### ISSUE TITLE
AutoFarm TDS

### ISSUE THREAD

**Issue by TheRealMajner** [banbuskox/Scripts#1]
stuck at difficulty selection

**Comment by banbuskox** [comment]
> stuck at difficulty selection

man, if u don't know how to use it, don't use it. If u fount it on the internet just don't use it, https://github.com/banbuskox/Scripts/blob/master/AutoFarm%20TDS%20Config

**Comment by TheRealMajner** [comment]
Dude i know there is a config and i configurated it i injected it then I
was waiting 10 s got teleported to elevator with game then another few
seconds then I was teleported and your script got stucked at level
difficulty selection and nope I’m not retarded to don’t know how to use
freakin lua scripts I’d rather code c#/c++ on my own when you’re toxic and
not able to help or investigate this issue.
Good luck with further development

čtvrtek 5. listopadu 2020 banbuskox <notifications@github.com> napsal(a):

**Comment by banbuskox** [comment]
Ok, then add me on discord for help : banbus#0001

czw., 5 lis 2020, 22:32 użytkownik Lukas Zamyslicky <
notifications@github.com> napisał:
